[workspace]
members = [
    "examples/demo01_poisson_solver",
    "examples/demo02_nbody",
    "examples/demo03_opencl",
    "examples/demo04_wgpu_compute",
    "examples/demo05_pointer_reinterpret",
    "examples/demo06_opencl_opengl_interop",
    "examples/demo07_uff_forcefield",
    "examples/demo08_molecule_viewer",
    "examples/demo09_collision_debug",
    "examples/demo10_collision_balls",
    "mol_utils",
    "mol_topology",
    "mol_engine",
]
resolver = "2"

[workspace.dependencies]
eframe = { version = "0.29", default-features = false, features = ["default_fonts", "glow"] }
egui = "0.29"
egui_plot = "0.29"
ndarray = "0.16"
nalgebra = "0.33"
rand = "0.8"
ocl = "0.19"
wgpu = "24.0"
pollster = "0.4"
bytemuck = { version = "1.21", features = ["derive"] }
winit = "0.29"
